site_name: Team Deliverance Totesys Documentation
docs_dir: doc_src

nav:
  - Home: index.md
  - Ingestion:
      - Ingestion Lambda Utils: ingestion/lambda_utils.md
  - Processing:
      - Processing Lambda Utils: processing/lambda_utils.md
  - Loading:
      - Loading Lambda Utils: loading/lambda_utils.md
theme:
  name: material