name: CI

on:
  push:
    branches-ignore:
      - main
    paths:
      - '**.py'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run checks
        run: make run-checks

      - name: Run tests with coverage
        run: |
          coverage run -m pytest extract/tests/
          # Tests dont exist yet for below
          # coverage run -m pytest transform/tests/
          # coverage run -m pytest load/tests/
          coverage report -m

      - name: Run Black
        run: black --check .

      - name: Lint with flake8
        run: flake8 --config .flake8
